version: "3.8"

services:
  wallet_microservice:
    container_name: wallet_microservice
    build:
      context: ./
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
#      - "5555:5555"
#      - "7070:7070"
    environment:
      - PORT=5000
    depends_on:
      - rabbitmq
      - postgesql
    restart: always
    volumes:
      - ./:/app
    networks:
      - microservice_network

  postgesql:
    image: postgres:13-alpine
    container_name: postgesql_container
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - microservice_network

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge